### PR TITLE
Payload Validation

### PR DESCRIPTION
**Pull request by debbieneaeraconsulting**
Added complete validation of payload for BSM and TIM message types
  - Lists and arbitrarily nested lists are now supported
  - Validation for choice elements (only 1 object of a set is allowed) are now supported
  - EqualsValue logic now allows mandatory fields within optional fields
  - Added specific configuration files for BSM and TIM message types with payload fields
Added flexible date format parsing with the inclusion of a `DateFormat` parameter in configuration files for unusually formatted timestamps using python strftime strings
  - Example: For the timestamp `01-APR-17 12.02.17.833000000 AM` the proper `DateFormat` would be `%d-%b-%y %I.%M.%S.%f000 %p`
  - Documentation on how to create a python strftime format string can be found at `http://strftime.org/`
Updated README.md with release 0.0.7 notes

### CODE REVIEW

**Comment by debbieneaeraconsulting** [comment]
Travis CI error "sonar-scanner: command not found" is preventing Travis CI build

**Comment by debbieneaeraconsulting** [comment]
I commented the sonar cloud line from the travis.yml file to allow this forked branch to successfully build in travis.

**Comment by mvs5465** [comment]
Looks good. Thanks for adding to the readme. If you don't mind, lets uncomment the sonar-scanner line now that we know the build is passing. That way the Sonar report can run when we merge this.

**Comment by mvs5465** [comment]
Issue report created: https://github.com/usdot-jpo-ode/ode-output-validator-library/issues/35

**Pull request merged**
